# Generated by Django 5.0.6 on 2024-05-25 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=45, verbose_name='نام رشته')),
            ],
            options={
                'verbose_name': 'رشته',
                'verbose_name_plural': 'رشته ها',
            },
        ),
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='trhopy', max_length=30, verbose_name='عنوان')),
                ('image_path', models.CharField(default='no_photo.jpg', max_length=20)),
                ('desc', models.TextField(blank=True, verbose_name='توضیحات')),
                ('when_get', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ کسب عنوان')),
                ('slug', models.SlugField()),
                ('honor_field', models.CharField(choices=[('university', 'دانشگاهی'), ('compition', 'مسابقات'), ('olympi', 'المپیاد'), ('other', 'المپیاد')], max_length=20, verbose_name='دسته افتخار')),
            ],
            options={
                'verbose_name': 'افتخار',
                'verbose_name_plural': 'افتخارات',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
                ('family', models.CharField(max_length=20, verbose_name='نام خانوداگی')),
                ('slug', models.SlugField()),
                ('age', models.IntegerField(blank=True, verbose_name='سن')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='ایمیل')),
                ('education_degree', models.CharField(choices=[('under-diploma', 'زیر دیپلم'), ('diploma', 'دیپلم'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('Ph.d.', 'دکتری')], default='under-diploma', max_length=30, verbose_name='تحصیلات')),
                ('education_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one_image.field', verbose_name='رشته تحصیلی')),
            ],
            options={
                'verbose_name': 'دارنده افتخار',
                'verbose_name_plural': 'دارندگان افتخار',
            },
        ),
        migrations.DeleteModel(
            name='image',
        ),
        migrations.AddField(
            model_name='honor',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one_image.person', verbose_name='دارنده عنوان'),
        ),
    ]
