# Generated by Django 5.0.6 on 2024-05-25 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_image', '0003_institute_alter_honor_name_honor_who_give_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institute',
            options={'verbose_name': 'سازمان', 'verbose_name_plural': 'سازمان ها'},
        ),
        migrations.AlterField(
            model_name='honor',
            name='honor_field',
            field=models.CharField(choices=[('university', 'دانشگاهی'), ('compition', 'مسابقات'), ('olympi', 'المپیاد'), ('other', 'دیگر')], max_length=20, verbose_name='دسته افتخار'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='build_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='one_image.institute', verbose_name='از طرف'),
        ),
    ]
